-- Laboratorio Vega Ricambi: un solo file per procedure + trigger
CREATE PROCEDURE PRC_PRENOTA_ARTICOLO (
    P_ID_RICHIESTA IN NUMBER
) AS
BEGIN
    UPDATE RICHIESTA_RICAMBIO
       SET STATO = 'PRENOTATA'
     WHERE ID_RICHIESTA = P_ID_RICHIESTA;

    UPDATE ARTICOLO
       SET QTA_DISPONIBILE = QTA_DISPONIBILE - 1
     WHERE ID_ARTICOLO = (
        SELECT ID_ARTICOLO
          FROM RICHIESTA_RICAMBIO
         WHERE ID_RICHIESTA = P_ID_RICHIESTA
     );
END;
/

CREATE TRIGGER TRG_CHIUDI_RICHIESTA
BEFORE UPDATE OF STATO ON RICHIESTA_RICAMBIO
FOR EACH ROW
BEGIN
    IF :NEW.STATO = 'CHIUSA' AND :OLD.STATO <> 'CONSEGNATA' THEN
        RAISE_APPLICATION_ERROR(-20001, 'La richiesta deve essere consegnata prima della chiusura');
    END IF;
END;
/
